version: "3"
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 5000:80
    depends_on:
      - web


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: desafioflex
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: senha
      MYSQL_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  mysql_data:
